apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-servers
  labels:
    app: web-servers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-servers
  template:
    metadata:
      labels:
        app: web-servers
    spec:
      containers:
      - name: kubernetes-example
        image: sbrkrkmz/kubernetes-example:latest
        ports:
        - containerPort: 5555
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
            